directories:
  output: build
  buildResources: build
productName: 酷猫云盘管理器
appId: com.example.yourapp
files:
  - filter:
      - dist/electron/**/*
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: build/icons/icon.icns
win:
  icon: build/icons/icon.ico
linux:
  category: Utility
  icon: build/icons
  target:
    - AppImage
    - tar.gz
    - rpm
electronVersion: 2.0.4
